#!/usr/bin/env python3
import argparse

def main():
  parser = argparse.ArgumentParser()

  parser.add_argument("-i", "--id", help="get id")
  parser.add_argument("-q", "--query", help="get query")

  args = parser.parse_args()
  if args.id:
    print(args.id)
  if args.query:
    print(args.query)

if __name__ == "__main__":
  main()
